import MainPagePicture from '../../../public/img/main-page-picture.svg';
import DiaryBigPicture from '../../../public/img/diary-big-picture.svg';
import RepeatBigPicture from '../../../public/img/repeat-big-picture.svg';
import HamburgerMenuPicture from '../../../public/img/hamburger-menu.svg';
import Spread from '../../../public/img/spread.svg';
import Collaboration from '../../../public/img/collaboration.svg';
import Analytics from '../../../public/img/analytics.svg';
import Success from '../../../public/img/success.svg';
import Application from '../../../public/img/application.svg';
import Close from '../../../public/img/close.svg';
import Bell from '../../../public/img/bell.svg';
import Home from '../../../public/img/home.svg';
import Practice from '../../../public/img/practice.svg';
import Rating from '../../../public/img/rating.svg';
import Dictionary from '../../../public/img/dictionary.svg';
import Statistics from '../../../public/img/statistics.svg';
import Settings from '../../../public/img/settings.svg';

export const MainPagePictureImage = MainPagePicture;
export const DiaryBigPictureImage = DiaryBigPicture;
export const RepeatBigPictureImage = RepeatBigPicture;
export const HamburgerMenuPictureImage = HamburgerMenuPicture;
export const SpreadImage = Spread;
export const CollaborationImage = Collaboration;
export const AnalyticsImageImage = Analytics;
export const SuccessImage = Success;
export const ApplicationImage = Application;
export const CloseImage = Close;
export const BellImage = Bell;
export const HomeImage = Home;
export const PracticeImage = Practice;
export const RatingImage = Rating;
export const DictionaryImage = Dictionary;
export const StatisticsImage = Statistics;
export const SettingsImage = Settings;
